name: crawl

on:
  schedule:
    - cron: '*/42 * * * *`
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: node src/mirror.js

      - name: commit index
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/index.html
          git diff --cached --quiet || git commit -m "crawl"
          git push
